# app/main.py
import uuid
from typing import Optional
from fastapi import FastAPI, HTTPException
from fastapi.middleware.cors import CORSMiddleware
from pydantic import BaseModel, Field
from langchain_core.messages import HumanMessage

# Import configuration adapters and graph executors cleanly from brother subpackages
from app.core.config import settings
from app.agents.graph import get_redis_saver, get_runtime_agent_brain
from app.services.git_ingestion import ingest_github_repository

app = FastAPI(title="ContextEngine Core API Gateway")

# Setup aggressive wide-open CORS allowance filters for local Vite port mapping runs
app.add_middleware(
    CORSMiddleware,
    allow_origins=["*"],
    allow_credentials=True,
    allow_methods=["*"],
    allow_headers=["*"],
)

# ==========================================
# PYDANTIC REQ/RES TRANSACTION SCHEMAS
# ==========================================
class ChatRequest(BaseModel):
    message: str = Field(..., description="The user question parsed out from currentInput text entry")
    thread_id: Optional[str] = Field(None, description="The continuous chat session multi-turn history cookie tracking index token")

class ChatResponse(BaseModel):
    response: str
    thread_id: str
    router_decision: str

class GitIndexRequest(BaseModel):
    repo_url: str = Field(..., description="The absolute target public GitHub repository URL link location string")
    branch: Optional[str] = Field("main", description="The development tracking branch pipeline stream layer to checkout and vectorize")

# ==========================================
# REST API GATEWAY ROUTER ENDPOINTS
# ==========================================
@app.post("/api/chat", response_model=ChatResponse)
async def chat_endpoint(payload: ChatRequest):
    """Processes natural language requests, running through the agentic graph state nodes."""
    user_message = payload.message
    thread_id = payload.thread_id or str(uuid.uuid4())
    config = {"configurable": {"thread_id": thread_id}}
    
    async with get_redis_saver() as saver:
        try:
            # Explicitly provision internal checkpointer indexing properties inside Redis Stack memory
            await saver.asetup()
            
            agent_executor = await get_runtime_agent_brain(saver)
            inputs = {"messages": [HumanMessage(content=user_message)]}
            final_state = await agent_executor.ainvoke(inputs, config=config)
            
            return ChatResponse(
                response=final_state.get("final_output", "Error: No response generated by agent nodes backend loop."),
                thread_id=thread_id,
                router_decision=final_state.get("router_decision", "vector_db")
            )
        except Exception as e:
            print(f"Internal Pipeline Execution Crash: {str(e)}", flush=True)
            raise HTTPException(status_code=500, detail=f"Agent Graph Failure: {str(e)}")

@app.post("/api/index-git")
async def index_git_endpoint(payload: GitIndexRequest):
    """Triggers the remote scratchpad cloning, parsing, and Qdrant vectorization pipeline task."""
    repo_target = payload.repo_url.strip()
    branch_target = payload.branch or "main"
    
    print(f"Received React User Web Request to index remote workspace: {repo_target}", flush=True)
    
    try:
        # Pass parameters directly into our hardened GitPython extraction pipeline service
        result_log = ingest_github_repository(repo_target, branch=branch_target)
        
        if "Success" in result_log or "✅" in result_log:
            return {"status": "success", "message": result_log}
            
        # If it returns an explicit error string or fails silent validation metrics
        raise HTTPException(status_code=400, detail=result_log)
        
    except Exception as err:
        print(f"Remote Git Engine Task Injection Crash: {str(err)}", flush=True)
        raise HTTPException(status_code=500, detail=f"Git Extraction Pipeline Failure: {str(err)}")
